### ISSUE TITLE
Performance issue in converting excel to json

### ISSUE THREAD

**Issue by Anmolk22** [SheetJS/SheetJS.github.io#12]
```js
var data = new Uint8Array(arraybuffer);
  var arr = new Array();
  for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
  var bstr = arr.join("");

  /* Call XLSX */
  var workbook = XLSX.read(bstr, {type:"binary"});
```

I am working converting an excel sheet to json. this excel sheet contains 2000 rows and 6 columns I am using fileReader on ie11 and I followed the demo in the documentation and it is working fine for 100 columns but it gets stuck for this excel. Can we optimize it any how

**Comment by SheetJSDev** [comment]
Can you share a file?

**Comment by Anmolk22** [comment]
[Test.xlsx](https://github.com/SheetJS/SheetJS.github.io/files/1212273/Test.xlsx)

**Comment by SheetJSDev** [comment]
This file appears to work on the demos in http://oss.sheetjs.com/ and http://oss.sheetjs.com/js-xlsx (tested with IE11 update version 11.0.31) -- can you test if those pages work with your file?  If you are still having issues, please raise an issue in the xlsx issue tracker https://github.com/sheetjs/js-xlsx

**Comment by Anmolk22** [comment]
The code you tested it on contains the same implementation as the documentation
